export const mainProducts = [
  {
    id: 1,
    title: "Beginning C++ Programming - From Beginner to Beyond",
    image: "https://wallpapercave.com/dwp1x/wp4009913.png",
    price: 11.96,
    category: "Service",
    rating: 4,
    instructor: "Dr. Frank Mitropoulos",
    description:
      "Obtain Modern C++ Object-Oriented Programming (OOP) and STL skills. C++14 and C++17 covered. C++20 info see below.",
    duration: 2,
    content: [
      {
        id: 1,
        title: "Introduction",
        lectures: 3,
        duration: 2,
      },
      {
        id: 2,
        title: "Installation and Setup",
        lectures: 4,
        duration: 1,
      },
      {
        id: 3,
        title: "Structure of C++ Programs",
        lectures: 5,
        duration: 2,
      },
      {
        id: 4,
        title: "Variables and Constants",
        lectures: 4,
        duration: 2,
      },
      {
        id: 5,
        title: "Arrays and Vectors",
        lectures: 7,
        duration: 3,
      },
      {
        id: 6,
        title: "Statements and Operators",
        lectures: 3,
        duration: 5,
      },
      {
        id: 7,
        title: "Controlling Program Flow",
        lectures: 6,
        duration: 2,
      },
    ],
  },
  {
    id: 2,
    title: "Complete C# Unity Game Developer 3D",
    image: "https://mcdn.wallpapersafari.com/medium/37/44/Elas7y.jpg",
    price: 15.96,
    category: "Service",
    rating: 4,
    instructor: "Omar",
    description:
      "Design & Develop Video Games. Learn C# in Unity Engine. Code Your first 3D Unity games for web, Mac & PC.",
    duration: 2,
    content: [
      {
        id: 1,
        title: "Introduction & Setup",
        lectures: 5,
        duration: 2,
      },
      {
        id: 2,
        title: "Project Boost",
        lectures: 8,
        duration: 5,
      },
      {
        id: 3,
        title: "Argon Assault",
        lectures: 6,
        duration: 3,
      },
      {
        id: 4,
        title: "Real Rush",
        lectures: 11,
        duration: 6,
      },
      {
        id: 5,
        title: "Data Structures",
        lectures: 5,
        duration: 6,
      },
      {
        id: 6,
        title: "Zombie Runner - First Person Shooter",
        lectures: 13,
        duration: 8,
      },
      {
        id: 7,
        title: "Continuing your GameDev Journey",
        lectures: 2,
        duration: 1,
      },
    ],
  },
  {
    id: 3,
    title: "Java Programming Masterclass covering Java 11 & Java 17",
    image:
      "https://c4.wallpaperflare.com/wallpaper/284/730/367/computers-1920x1200-java-wallpaper-preview.jpg",
    price: 23.96,
    category: "Products",
    rating: 3,
    instructor: "Chloey Jennings",
    description:
      "Learn Java In This Course And Become a Computer Programmer. Obtain valuable Core Java Skills And Java Certification",
    duration: 2,
    content: [
      {
        id: 1,
        title: "Course Introduction",
        lectures: 6,
        duration: 2,
      },
      {
        id: 2,
        title: "Software Tools Setup",
        lectures: 4,
        duration: 1,
      },
      {
        id: 3,
        title: "First Steps",
        lectures: 5,
        duration: 3,
      },
      {
        id: 4,
        title: "Expressions, Statements, Code blocks, Methods and More",
        lectures: 12,
        duration: 6,
      },
      {
        id: 5,
        title: "Control Flow Statements",
        lectures: 5,
        duration: 3,
      },
      {
        id: 6,
        title: "Object Oriented Programming",
        lectures: 18,
        duration: 7,
      },
      {
        id: 7,
        title: "Arrays, Lists, Autoboxing, and Unboxing",
        lectures: 9,
        duration: 4,
      },
    ],
  },
  {
    id: 4,
    title: "Complete guide to ASP.NET Core MVC (.NET 6)",
    image:
      "https://bestcloudhostingasp.net/wp-content/uploads/asp-net-core-identity-with-patterns.jpg",
    price: 9.96,
    category: "Services",
    rating: 5,
    instructor: "Jackson Maddison",
    description:
      "Build real world application using ASP.NET Core MVC, Entity Framework Core and ASP.NET Core Identity.",
    duration: 2,
    content: [
      {
        id: 1,
        title: "Introduction",
        lectures: 4,
        duration: 2,
      },
      {
        id: 2,
        title: "MVC Basics",
        lectures: 6,
        duration: 4,
      },
      {
        id: 3,
        title: "Razor Pages",
        lectures: 4,
        duration: 2,
      },
      {
        id: 4,
        title: "N-ier Architecture",
        lectures: 8,
        duration: 5,
      },
      {
        id: 5,
        title: "Repository Pattern",
        lectures: 5,
        duration: 2,
      },
      {
        id: 6,
        title: "Home Page",
        lectures: 4,
        duration: 3,
      },
      {
        id: 7,
        title: "Shopping Cart",
        lectures: 3,
        duration: 2,
      },
      {
        id: 8,
        title: "Order Creation",
        lectures: 8,
        duration: 4,
      },
    ],
  },
  {
    id: 5,
    title: "Vue - The Complete Guide (incl. Router & Composition API)",
    image: "https://wallpaperaccess.com/full/4584343.jpg",
    price: 19.96,
    category: "Counselling",
    rating: 3,
    instructor: "Austin Hull",
    description: "here descrscsdsxcs",
    duration: 2,
    content: [
      {
        id: 1,
        title: "Getting Started",
        lectures: 2,
        duration: 1,
      },
      {
        id: 2,
        title: "Basics & Core Concepts",
        lectures: 5,
        duration: 6,
      },
      {
        id: 3,
        title: "Conditional Rendering",
        lectures: 2,
        duration: 3,
      },
      {
        id: 4,
        title: "Components",
        lectures: 4,
        duration: 5,
      },
      {
        id: 5,
        title: "Behing the Scenes",
        lectures: 2,
        duration: 3,
      },
      {
        id: 6,
        title: "Components Communication",
        lectures: 2,
        duration: 4,
      },
      {
        id: 7,
        title: "Course Project",
        lectures: 5,
        duration: 7,
      },
    ],
  },
];

export const bannerImg =
  "https://images-eu.ssl-images-amazon.com/images/G/02/digital/video/merch2016/Hero/Covid19/Generic/GWBleedingHero_ENG_COVIDUPDATE__XSite_1500x600_PV_en-GB._CB428684220_.jpg";
