name: CI
on:
  push:
    branches:
      - master
jobs:
  run-linters:
    name: lint Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository # The first step of most actions is going to
        uses: actions/checkout@v2 # use this plugin to clone the repo to the virtual machine

      - name: Set up Node.js # Secondarily because this is a javascript ecosystem we need to install node
        uses: actions/setup-node@v1 # This plugin takes care of that for us
        with:
          node-version: 12 # Some plugins allow for configuration like this

      # Install our packages now that we have node
      - name: Install Node.js dependencies
        run: npm install # I use npx here so I don't have to install yarn globally on this VM

      # Lint the folder system
      - name: Lint Code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      # Speed up subsequent runs with caching
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Install required deps for action
      - name: Install Dependencies
        run: npm install

      # Finally, run our tests
      - name: Run the tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [test, run-linters]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "qtech2022" #Must be unique in Heroku
          heroku_email: "yabani4ever@gmail.com"

      #- name: Run the linting
      #  run: npm eslint
